[build]
builder = "NIXPACKS"
buildCommand = "NPM_CONFIG_CACHE=/tmp/npm-cache npm ci --no-audit --no-fund && npm run build"
outputDirectory = "dist"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300

[[services]]
name = "vitan-task-frontend"
type = "static"
directory = "dist"
fallback = "index.html"

[static]
directory = "dist"
fallback = "index.html"
