[build]
builder = "NIXPACKS"
buildCommand = "BROWSERSLIST_CACHE=/tmp/browserslist-cache XDG_CACHE_HOME=/tmp NPM_CONFIG_CACHE=/tmp/npm-cache npm run build"
outputDirectory = "dist"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300

[[services]]
name = "vitan-task-frontend"
type = "static"
directory = "dist"
fallback = "index.html"

[static]
directory = "dist"
fallback = "index.html"
