name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd frontend
          npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          BACKEND_BASE: https://vitan-task-backend-production.up.railway.app
          VITE_NO_AUTH: true
          VITE_DEV_MODE: true
        run: |
          cd frontend
          npx playwright test --reporter=line

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-tests-screenshots
          path: frontend/tests/__screenshots__/
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Playwright screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: frontend/tests/__screenshots__

