name: web-ci
on: [push, pull_request]

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --no-audit --no-fund
      
    - name: Type check
      run: npm run typecheck
      
    - name: Build application
      run: npm run build
      
    - name: Run smoke tests
      run: VITE_API_BASE_URL=https://vitan-task-production.up.railway.app npm run smoke
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: dist/
        retention-days: 7
